donate_page/urls.py
from django.urls import path
from .views import *

app_name = 'donate_page'
urlpatterns = [
    path('<str:titleURL>/', disasterInfo, name='disasterInfo'),
    path('allDonation', allDonation, name='allDonation')
]

form_page/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<str:titleURL>/', form_page, name='donasi'),
    path('thankyou', thankyou_page, name='thankyou'),
]

ppw_tugas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('registrasi/', include('regis_page.urls')),
    path('donasi/', include('form_page.urls')),
    path('disasterInfo/', include('donate_page.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('donasi-saya/', include('listdonasi_page.urls')),
]

handler404 = home_page.views.handler404
handler500 = home_page.views.handler500

regis_page/urls.py
from django.urls import path
from . import views

app_name = 'regis_page'

urlpatterns = [
    path('', views.register, name='form'),
    path('logoutview', views.logoutview, name='logoutview'),
]

templates/import.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Hind" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <a class="navbar-brand" href="{% url 'homepage' %}">SinarPerak</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" id="link-to-news" href="{% url 'homepage' %}#news">Berita</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'donate_page:allDonation' %}">Donasi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">Tentang Kami</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Hello, {{ user.first_name }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'list_donasi' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'regis_page:logoutview' %}">Log Out</a>
                    </div>
                {% else %}
                    <a class="nav-link" href="{% url 'regis_page:form' %}">Daftar</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>